# system information
os: linux
dist: trusty
sudo: require
language: cpp

# notification settings
notifications:
  email:
    recipients:
      - dasayan05@hotmail.com
    on_success: change
    on_failure: always

matrix:
  include:
      - compiler: g++-5
        addons:
          apt:
            packages:
             - g++-5
            sources:
             - ubuntu-toolchain-r-test
        env:
         - BUILD_TYPE_ENV="CMAKE_BUILD_TYPE=Debug"
         - MATRIX_ENV_CXX="CXX=g++-5"

      - compiler: g++-5
        addons:
          apt:
            packages:
             - g++-5
            sources:
             - ubuntu-toolchain-r-test
        env:
         - BUILD_TYPE_ENV="CMAKE_BUILD_TYPE=Release"
         - MATRIX_ENV_CXX="CXX=g++-5"

before_script:
    - eval "${MATRIX_ENV_CXX}"
    - eval "${BUILD_TYPE_ENV}"
    
    # setup GoogleTest
    - sudo apt-get -qq update
    - sudo apt-get install -y cmake libblas-dev liblapack-dev liblapacke-dev libopenblas-dev libopenblas-base gfortran
    - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
    - sudo tar xf release-1.8.0.tar.gz
    - cd googletest-release-1.8.0
    - sudo cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON .
    - sudo make -j`nproc`
    - sudo cp -a googletest/include/gtest /usr/include
    - sudo cp -a googletest/libgtest*.a /usr/lib/
    - cd ..
    
    # create build directory for CMake
    # generation and cd into it
    - mkdir build
    - cd build

script:
    - cmake .. -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    - make -j`nproc`
    - ctest -V
    - sh travisrunner.sh
